In [34]:
import pandas as pd
import numpy as np
orders = pd.read_csv("pandas_aggregates.csv")
print(orders.head(), "\n")

#find most expensive price
most_expensive = orders.price.max()
print(most_expensive, "\n")

#number of (unique) shoe colors in the inventory
num_colors = orders.shoe_color.nunique()
print(num_colors, "\n")

#most expensive shoes by shoe_type
pricey_shoes = orders.groupby("shoe_type").price.max()
print(pricey_shoes, "\n")

#returning a nice looking DataFrame using .reset_index() 
pricey_shoes = orders.groupby('shoe_type').price.max().reset_index()
print(pricey_shoes, "\n")

#calculate the 25th percentile for shoe price for each shoe_color
cheap_shoes= orders.groupby("shoe_color").price.apply(lambda x: np.percentile(x, 25)).reset_index()
print(cheap_shoes, "\n")

#Create a DataFrame with the total number of shoes of each shoe_type/shoe_color combination purchased. 
#Save it to the variable shoe_counts.

shoe_counts = orders.groupby(["shoe_type","shoe_color"])["id"].count().reset_index()
print(shoe_counts, "\n")

#create shoe_counts PIVOT Table
shoe_counts_pivot = shoe_counts.pivot(
    columns = "shoe_color",
    index = "shoe_type",
    values = "id"
).reset_index() #looks better without reset_index though...
print(shoe_counts_pivot, "\n")

      id first_name last_name                       email  shoe_type  \
0  97916    Douglas     Perez    DouglasPerez28@gmail.com  stilettos
1  67691    Tiffany   O'neill  TiffanyO'neill51@gmail.com     wedges
2  72818      Susan     Rivas       Susan.Rivas@gmail.com    sandals
3  28080     Angela    Hopper  AngelaHopper62@outlook.com  stilettos
4  89958     Thomas  Benjamin     TBenjamin1981@gmail.com    sandals

  shoe_material shoe_color  price
0        fabric      brown     90
1       leather       navy     94
2  faux-leather      white     96
3       leather        red     96
4  faux-leather       navy     97

498

5

shoe_type
ballet flats    498
sandals         498
stilettos       468
wedges          488
Name: price, dtype: int64

      shoe_type  price
0  ballet flats    498
1       sandals    498
2     stilettos    468
3        wedges    488

  shoe_color  price
0      black  130.0
1      brown  248.0
2       navy  200.0
3        red  157.0
4      white  188.0

       shoe_type shoe_color  id
0   ballet flats      black   2
1   ballet flats      brown  11
2   ballet flats       navy  17
3   ballet flats        red  13
4   ballet flats      white   7
5        sandals      black   3
6        sandals      brown  10
7        sandals       navy  13
8        sandals        red  14
9        sandals      white  10
10     stilettos      black   8
11     stilettos      brown  14
12     stilettos       navy   7
13     stilettos        red  16
14     stilettos      white   5
15        wedges      brown  13
16        wedges       navy  16
17        wedges        red   4
18        wedges      white  17

shoe_color     shoe_type  black  brown  navy   red  white
0           ballet flats    2.0   11.0  17.0  13.0    7.0
1                sandals    3.0   10.0  13.0  14.0   10.0
2              stilettos    8.0   14.0   7.0  16.0    5.0
3                 wedges    NaN   13.0  16.0   4.0   17.0